name: Nuget Package Deploy

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build with dotnet
        run: dotnet build --configuration Release
      - name: Test with dotnet
        run: dotnet test --configuration Release
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Push package to nuget
        uses: alirezanet/publish-nuget@v3.0.0
        with:
          PROJECT_FILE_PATH: AdifLib/AdifLib.csproj
          VERSION_REGEX: <Version>(.*)<\/Version>
          TAG_COMMIT: false
          INCLUDE_SYMBOLS: true
          NUGET_KEY: ${{secrets.NUGET_DEPLOY_KEY}}        
